[build]
  base = "agriassist-pro"
  publish = "dist"
  command = "npm run build"
  environment = { SECRETS_SCAN_OMIT_KEYS = "VITE_CLERK_PUBLISHABLE_KEY,VITE_GEMINI_API_KEY,VITE_SUPABASE_URL,VITE_SUPABASE_ANON_KEY" }

[[headers]]
  for = "*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "*.tsx"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "*.ts"
  [headers.values]
    Content-Type = "application/javascript"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200